# the name of the command or function you're documenting
name="something_else"
# a short (one line) description of what it does
short_description="something_else test description sedescription"
description="""
To go into the full details of something_else could take nanoseconds
or less, because it doesn't exist. On the other hand, I could
spend many words (far more than I shall) to descript the fullness
of the non-existent situation. Here, in the middle ground, we
see just enough, to let us know that there's a "real" description here.
"""
# if the tool has some sort of usage / help documentation you can
# invoke, enter it in the usage_command. Otherwise, comment that out,
# and document it in the fallback_usage. In TOML you can create a
# multiline string by surrounding it with triple double quotes.
# """ like this """
# usage_command="dgrep"
fallback_usage="""
something_else demo usage
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url=""
# where you can find the repo that contains this file
source_repo_url=""
tags=["se1", "se2"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
